import { makeFixture, inspectPem, signPss, normalizePem } from "./crypto.js";
const REST_URL="https://api.elections.kalshi.com/trade-api/v2/portfolio/balance";
const REST_PATH="/trade-api/v2/portfolio/balance";
const WS_URL="wss://api.elections.kalshi.com/trade-api/ws/v2";
const WS_PATH="/trade-api/ws/v2";
const caps={readOnly:true,tradingCapability:false,orderCapability:false,cancellationCapability:false,transferCapability:false,bankrollCapability:false,baselineBindingPresent:false};
function shape(env){const id=String(env.UMEO_CLEAN_KEY_ID??"").trim(), key=String(env.UMEO_CLEAN_PRIVATE_KEY??"");return {keyIdPresent:!!id,keyIdLength:id.length,keyIdLooksUuid:/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id),privateKeyPresent:!!key,scope:String(env.UMEO_CLEAN_SCOPE??"").trim(),...caps};}
function signed(env,path){if(String(env.UMEO_CLEAN_SCOPE??"").trim()!=="read")throw new Error("READ_ONLY_SCOPE_REQUIRED");const id=String(env.UMEO_CLEAN_KEY_ID??"").trim();const pem=normalizePem(env.UMEO_CLEAN_PRIVATE_KEY);const ts=Date.now().toString();const s=signPss(pem,ts+"GET"+path);if(!s.localVerified)throw new Error("LOCAL_VERIFY_FAILED");return {headers:{"KALSHI-ACCESS-KEY":id,"KALSHI-ACCESS-TIMESTAMP":ts,"KALSHI-ACCESS-SIGNATURE":s.signature},proof:{keyType:s.keyType,localVerified:s.localVerified}};}
async function rest(env){try{const a=signed(env,REST_PATH);const r=await fetch(REST_URL,{headers:a.headers});return {ok:r.ok,httpStatus:r.status,providerBody:await r.text(),local:a.proof,...caps};}catch(e){return {ok:false,failure:String(e?.message||e),...caps};}}
async function websocket(env){try{const a=signed(env,WS_PATH);const r=await fetch(WS_URL,{headers:{...a.headers,Upgrade:"websocket"}});if(r.status!==101||!r.webSocket)return {ok:false,httpStatus:r.status,failure:await r.text(),local:a.proof,...caps};const ws=r.webSocket;ws.accept();ws.send(JSON.stringify({id:1,cmd:"subscribe",params:{channels:["ticker"]}}));const result=await new Promise(resolve=>{const timer=setTimeout(()=>resolve({ok:false,failure:"TICKER_TIMEOUT"}),10000);ws.addEventListener("message",ev=>{let m;try{m=JSON.parse(ev.data);}catch{return;}if(m?.type==="subscribed"||m?.type==="ticker"){if(m.type==="ticker"){clearTimeout(timer);resolve({ok:true,subscriptionAcknowledged:true,genuineTicker:true,tickerType:m.type});}}});ws.addEventListener("close",()=>{clearTimeout(timer);resolve({ok:false,failure:"WS_CLOSED"});});});try{ws.close(1000,"done");}catch{}return {...result,local:a.proof,...caps};}catch(e){return {ok:false,failure:String(e?.message||e),...caps};}}
export default {async fetch(req,env){const p=new URL(req.url).pathname;if(p==="/health")return Response.json({ok:true,worker:"umeo-auth-clean-v1",...caps});if(p==="/fixture-proof"){try{const pem=makeFixture();const parsed=inspectPem(pem);const signed=signPss(pem,"fixture-proof");return Response.json({ok:parsed.keyType==="rsa"&&signed.localVerified,fixturePemParse:parsed.keyType==="rsa",rsaPssSign:true,localVerify:signed.localVerified,readOnlyBoundary:true,...caps});}catch(e){return Response.json({ok:false,failure:String(e?.message||e),...caps},{status:500});}}if(p==="/credential-shape")return Response.json(shape(env));if(p==="/rest-auth")return Response.json(await rest(env));if(p==="/ws-acceptance")return Response.json(await websocket(env));return Response.json({ok:false,error:"NOT_FOUND",...caps},{status:404});}};
